language: java
os:
  - linux
dist: trusty
jdk:
  - oraclejdk8
before_install:
  - export TZ=Brazil/East
deploy:
  provider: heroku
  strategy: api
  api_key:
    secure: '69d2e20f-0595-4704-a3c6-4ad91df04eb5'
  app: 'jeferson-wallet'